### ISSUE TITLE
uri normalisations fails on md-ingest

### ISSUE THREAD

**Issue by csae8092** [acdh-oeaw/arche-assets#16]
using https://github.com/acdh-oeaw/arche-localhost-utils

try to ingest following snippet

```ttl
<https://www.wikidata.org/wiki/Q932005> a acdh:Place ;
    acdh:hasTitle "Habsburgische Erblande"@de ;
    acdh:hasTitle "Habsburg Hereditary Lands"@en .

<acdhid:foo> a acdh:TopCollection ;
    acdh:hasSpatialCoverage <http://www.wikidata.org/wiki/Q932005> .
```

fails do to 
> Transaction created resources without any metadata: http://127.0.0.1/api/11423, http://www.wikidata.org/wiki/Q932005

after correcting `http://www.wikidata.org/wiki/Q932005` to `http://www.wikidata.org/entity/Q932005` everything is fine

but this normalisation should be done arche on ingest?

**Comment by zozlak** [comment]
Hm... it seems to be the https://github.com/acdh-oeaw/arche-doorkeeper/issues/28 and there is even a test checking if it works... looking deeper.

**Comment by zozlak** [comment]
Can't replicate. As we will all be in the office until Wednesday, I'll come to you and look at your local config.

**Comment by zozlak** [comment]
Turned out to be a matter of @csae8092 local config.
